import { useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, BarChart3, CheckCircle2, ChevronLeft, ChevronRight, CircleHelp, Download, FileInput, Info, Menu, Search, ShieldCheck, Upload, X } from "lucide-react";
import { delta, demoReport, euroK, parseWorkbook } from "./domain";
import type { Decision, Metric, MetricKey, ReportData, Status } from "./domain";

type ScreenId = "summary" | "sales" | "ebitda" | "units" | "wc" | "decisions";
const screens: { id: ScreenId; label: string; conclusion: string }[] = [
  { id: "summary", label: "Síntese", conclusion: "Compare julho, agosto e o acumulado antes de discutir causas." },
  { id: "sales", label: "Vendas e margem", conclusion: "Separe o desvio de vendas do desvio de margem face ao orçamento." },
  { id: "ebitda", label: "EBITDA", conclusion: "A ponte reconcilia o orçamento de agosto ao EBITDA real." },
  { id: "units", label: "Unidades", conclusion: "O resultado por unidade é uma leitura de P&L — não equivale a EBITDA." },
  { id: "wc", label: "Working Capital", conclusion: "Explique o movimento entre clientes, inventário, fornecedores e caixa." },
  { id: "decisions", label: "Decisões", conclusion: "Feche questões com evidência, responsável e prazo." },
];
const initialDecision: Decision = { id: "initial", question: "Que explicação suporta o principal desvio de agosto?", answer: "", status: "Por validar", owner: "", deadline: "" };

function MetricCard({ metric, compare, onInfo }: { metric: Metric; compare?: Metric; onInfo: (metric: Metric) => void }) {
  const difference = delta(metric.value, compare?.value);
  return <article className="metric-card"><div className="metric-top"><span>{metric.label}</span><button onClick={() => onInfo(metric)} aria-label={`Definição e origem de ${metric.label}`}><Info size={16} /> Definição</button></div><strong>{euroK(metric.value)}</strong>{compare && <small className={difference != null && difference >= 0 ? "positive" : "negative"}>{difference != null && difference >= 0 ? "+" : ""}{euroK(difference)} <em>vs. {compare.label === "Orçamento" ? "orçamento" : "julho"}</em></small>}<span className="metric-source">{metric.source}</span></article>;
}
function ValueBars({ data, label }: { data: { label: string; value: number }[]; label: string }) {
  const max = Math.max(1, ...data.map(({ value }) => Math.abs(value)));
  return <figure className="chart"><figcaption>{label}</figcaption><div className="bar-chart">{data.map(({ label: itemLabel, value }) => <div className="bar-item" key={itemLabel}><b>{euroK(value)}</b><i style={{ height: `${Math.max(5, Math.abs(value) / max * 100)}%` }} className={value < 0 ? "down" : ""} /><span>{itemLabel}</span></div>)}</div></figure>;
}
function Bridge({ data }: { data: { label: string; value: number }[] }) { return <figure className="bridge"><figcaption>Contribuição para o EBITDA de agosto</figcaption><div>{data.map((item, index) => <article key={item.label} className={index === 0 || index === data.length - 1 ? "total" : item.value >= 0 ? "up" : "down"}><span>{item.label}</span><b>{index === 0 || index === data.length - 1 ? euroK(item.value) : `${item.value >= 0 ? "+" : ""}${euroK(item.value)}`}</b></article>)}</div><small>Componentes calculados a partir de movimentos elegíveis da folha Dados.</small></figure>; }
function Questions({ prompts, decisions, onAdd }: { prompts: string[]; decisions: Decision[]; onAdd: (question: string) => void }) { return <section className="questions"><h3>Questões comerciais</h3>{prompts.map((prompt) => <button key={prompt} onClick={() => onAdd(prompt)}><CircleHelp size={16} />{prompt}</button>)}{decisions.length > 1 && <small>{decisions.length - 1} questão(ões) adicionada(s) à ata.</small>}</section>; }

export default function App() {
  const [report, setReport] = useState<ReportData>(demoReport); const [screen, setScreen] = useState<ScreenId>("summary"); const [mode, setMode] = useState<"present" | "explore">("present"); const [info, setInfo] = useState<Metric | null>(null); const [message, setMessage] = useState(""); const [navOpen, setNavOpen] = useState(false); const inputRef = useRef<HTMLInputElement>(null);
  const [decisions, setDecisions] = useState<Decision[]>(() => { try { return JSON.parse(localStorage.getItem("uhc-resultados-notes-v1") ?? "null") ?? [initialDecision]; } catch { return [initialDecision]; } });
  useEffect(() => localStorage.setItem("uhc-resultados-notes-v1", JSON.stringify(decisions)), [decisions]);
  const current = screens.findIndex((item) => item.id === screen); const july = report.periods.jul; const august = report.periods.aug; const ytd = report.periods.ytd;
  const update = (id: string, patch: Partial<Decision>) => setDecisions((items) => items.map((item) => item.id === id ? { ...item, ...patch } : item));
  const addDecision = (question: string) => { setDecisions((items) => [...items, { ...initialDecision, id: crypto.randomUUID(), question }]); setScreen("decisions"); setMessage("Questão adicionada à ata local."); };
  const importWorkbook = async (file?: File) => { if (!file) return; try { setMessage("A processar localmente — o ficheiro não é enviado nem guardado."); setReport(await parseWorkbook(file)); setMessage("Importação concluída. Reveja os avisos de reconciliação."); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível importar o ficheiro."); } finally { if (inputRef.current) inputRef.current.value = ""; } };
  const exportMinutes = () => { const content = JSON.stringify({ exportedAt: new Date().toISOString(), report: report.fileName ?? "Demonstração fictícia", decisions }, null, 2); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([content], { type: "application/json" })); link.download = "ata-resultados-local.json"; link.click(); URL.revokeObjectURL(link.href); setMessage("Ata exportada. O ficheiro fica apenas no seu dispositivo."); };
  const importMinutes = async (file?: File) => { if (!file) return; try { const result = JSON.parse(await file.text()); if (!Array.isArray(result.decisions)) throw new Error("Formato de ata inválido."); setDecisions(result.decisions); setMessage("Ata local importada."); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível importar a ata."); } };
  const summaryCards: MetricKey[] = ["revenue", "grossMargin", "ebitda", "workingCapital", "cash"];
  const barValues = useMemo(() => [{ label: "Julho", value: july.revenue.value ?? 0 }, { label: "Agosto", value: august.revenue.value ?? 0 }, { label: "YTD agosto", value: ytd.revenue.value ?? 0 }], [july, august, ytd]);
  return <div className="app-shell">
    <aside className={`rail ${navOpen ? "open" : ""}`}><div className="brand"><strong>United Healthcare</strong><span>Distribuição</span></div><div className="mode-switch"><button className={mode === "present" ? "active" : ""} onClick={() => setMode("present")}><BarChart3 size={17} />Apresentar</button><button className={mode === "explore" ? "active" : ""} onClick={() => setMode("explore")}><Search size={17} />Explorar</button></div><nav aria-label="Percurso da reunião">{screens.map((item, index) => <button key={item.id} className={screen === item.id ? "active" : ""} onClick={() => { setScreen(item.id); setNavOpen(false); }}><b>{index + 1}</b><span>{item.label}</span></button>)}</nav><div className="rail-foot"><ShieldCheck size={16} /> Processamento local<br />Dados confidenciais</div></aside>
    <main><header className="topbar"><button className="menu" onClick={() => setNavOpen(!navOpen)} aria-label="Abrir navegação"><Menu size={21} /></button><span>{mode === "present" ? `Passo ${current + 1} de 6` : "Explorar definições e origem"}</span><div><button onClick={() => inputRef.current?.click()}><Upload size={16} /> Carregar XLSX</button><button onClick={exportMinutes}><Download size={16} /> Exportar ata</button></div></header>
      <section className="content"><div className="privacy"><ShieldCheck size={17} /><span>O XLSX é processado exclusivamente no seu navegador. Não é enviado nem guardado.</span></div>{message && <div className="notice"><CheckCircle2 size={17} />{message}<button onClick={() => setMessage("")} aria-label="Fechar"><X size={16} /></button></div>}
        <div className="page-heading"><div><p>{report.source === "demo" ? "Demonstração fictícia" : `Ficheiro local: ${report.fileName}`}</p><h1>{screens[current].label}</h1><h2>{screens[current].conclusion}</h2></div><div className="page-actions"><button className="primary" onClick={() => inputRef.current?.click()}><FileInput size={18} />Carregar ficheiro de resultados</button><input ref={inputRef} type="file" accept=".xlsx,.xls" hidden onChange={(e) => importWorkbook(e.target.files?.[0])} /></div></div>
        {screen === "summary" && <><section className="metric-grid">{summaryCards.map((key) => <MetricCard key={key} metric={august[key]} compare={july[key]} onInfo={setInfo} />)}</section><section className="split"><article className="conclusion"><h3>Leitura para a reunião</h3><p>Use esta página para fixar a diferença entre julho e agosto e enquadrar o acumulado. A análise de causas deve ficar registada na ata, com evidência e responsável.</p><button onClick={() => addDecision("Qual é a explicação confirmada para a variação mensal?")}>Registar explicação <ChevronRight size={16} /></button></article><ValueBars label="Receita por período" data={barValues} /></section></>}
        {screen === "sales" && <><section className="metric-grid three"><MetricCard metric={august.revenue} compare={{ ...august.revenue, label: "Orçamento", value: august.revenue.budget ?? null }} onInfo={setInfo} /><MetricCard metric={august.grossMargin} compare={{ ...august.grossMargin, label: "Orçamento", value: august.grossMargin.budget ?? null }} onInfo={setInfo} /><article className="metric-card"><div className="metric-top"><span>Margem sobre vendas de mercadorias</span><button onClick={() => setInfo(august.grossMargin)}><Info size={16} /> Definição</button></div><strong>{august.revenue.value ? `${((august.grossMargin.value ?? 0) / august.revenue.value * 100).toFixed(1)}%` : "Por validar"}</strong><span className="metric-source">Denominador: vendas de mercadorias</span></article></section><Questions decisions={decisions} onAdd={addDecision} prompts={["Que volumes, preços ou mix explicam o desvio de vendas?", "A margem foi afetada por custo, preço ou classificação?", "Que evidência suporta a explicação? "]} /></>}
        {screen === "ebitda" && <><Bridge data={report.bridge} /><section className="split"><article className="conclusion"><h3>Reconciliação</h3><p>O primeiro e o último bloco são totais. Os blocos intermédios representam efeitos face ao orçamento e devem reconciliar a ponte.</p></article><Questions decisions={decisions} onAdd={addDecision} prompts={["Que rubricas explicam o efeito Opex?", "Há movimentos não recorrentes a confirmar com o CFO?"]} /></section></>}
        {screen === "units" && <><section className="unit-list"><header><div><h3>Resultado por unidade</h3><p>Resultado de P&L atribuído à unidade. Não é EBITDA e não deve ser apresentado como tal.</p></div><button onClick={() => setInfo({ label: "Resultado por unidade", value: null, source: "Por Unidade / Dados", definition: "Resultado apresentado na folha Por Unidade; a sua definição contabilística pode diferir do EBITDA consolidado. Confirmar mapeamento com o CFO." })}><Info size={16} />Definição</button></header>{report.units.length ? report.units.map((unit) => <article key={unit.name}><span>{unit.name}</span><strong>{euroK(unit.result)}</strong><small>{unit.source}</small></article>) : <p className="missing">Por validar com o CFO: não foi possível identificar Trading, Unlicensed Medicines e Overhead nos movimentos importados.</p>}</section><Questions decisions={decisions} onAdd={addDecision} prompts={["A atribuição de resultado por unidade está completa?", "Que custos partilhados estão incluídos em Overhead?"]} /></>}
        {screen === "wc" && <><section className="metric-grid four"><MetricCard metric={august.workingCapital} compare={july.workingCapital} onInfo={setInfo} /><MetricCard metric={august.cash} compare={july.cash} onInfo={setInfo} /><article className="definition-card"><h3>Saldo contabilístico ≠ liquidez disponível</h3><p>Depósitos e caixa são saldos contabilísticos. Restrições, reconciliações bancárias ou utilização operacional requerem validação adicional.</p></article><article className="definition-card"><h3>Movimento de agosto</h3><p>Clientes, inventário e fornecedores devem justificar a alteração de Working Capital. Aging não está disponível neste ficheiro.</p></article></section><Questions decisions={decisions} onAdd={addDecision} prompts={["Que movimento de clientes explica a variação?", "Que decisão de inventário contribuiu?", "Fornecedores e depósitos/caixa estão reconciliados?"]} /></>}
        {screen === "decisions" && <section className="minutes"><header><div><h3>Ata local da reunião</h3><p>As notas ficam em localStorage deste navegador. Exporte-as para arquivo ou partilha controlada.</p></div><div><button onClick={() => setDecisions((items) => [...items, { ...initialDecision, id: crypto.randomUUID() }])}>Adicionar questão</button><label className="file-button">Importar ata<input type="file" accept="application/json" hidden onChange={(e) => importMinutes(e.target.files?.[0])} /></label></div></header>{decisions.map((item) => <article className="decision" key={item.id}><label>Questão<textarea value={item.question} onChange={(e) => update(item.id, { question: e.target.value })} /></label><label>Resposta<textarea value={item.answer} placeholder="Registe apenas factos ou indique a hipótese." onChange={(e) => update(item.id, { answer: e.target.value })} /></label><label>Estado<select value={item.status} onChange={(e) => update(item.id, { status: e.target.value as Status })}><option>Confirmado</option><option>Hipótese</option><option>Por validar</option></select></label><label>Responsável<input value={item.owner} onChange={(e) => update(item.id, { owner: e.target.value })} /></label><label>Prazo<input type="date" value={item.deadline} onChange={(e) => update(item.id, { deadline: e.target.value })} /></label></article>)}<button className="primary export" onClick={exportMinutes}><Download size={18} />Exportar ata local</button></section>}
        {mode === "explore" && <section className="explore"><h3>Verificações de dados</h3><div><span className={report.reconciled ? "ok" : "warn"}>{report.reconciled ? <CheckCircle2 size={16} /> : <AlertTriangle size={16} />}{report.reconciled ? "Meses de julho e agosto encontrados" : "Reconciliação completa por validar"}</span>{report.warnings.map((warning) => <p key={warning}>{warning}</p>)}</div><p><b>Fonte de verdade:</b> movimentos da folha Dados. Filtros aplicados: cenário, ano, mês, rubrica, BalPL e exclusão de SALDOS INICIAIS.</p></section>}
        <footer className="pager"><button disabled={current === 0} onClick={() => setScreen(screens[current - 1].id)}><ChevronLeft size={17} />Anterior</button><span>{current + 1} / {screens.length}</span><button disabled={current === screens.length - 1} onClick={() => setScreen(screens[current + 1].id)}>Seguinte<ChevronRight size={17} /></button></footer>
      </section></main>{info && <div className="modal-backdrop" role="presentation" onMouseDown={() => setInfo(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="definition-title" onMouseDown={(e) => e.stopPropagation()}><button className="close" onClick={() => setInfo(null)} aria-label="Fechar"><X size={18} /></button><p>Definição e origem</p><h2 id="definition-title">{info.label}</h2><p>{info.definition}</p><dl><dt>Origem</dt><dd>{info.source}</dd><dt>Classificação</dt><dd>Confidencial — processamento local</dd></dl></section></div>}</div>;
}
